# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.default]                                         # Define a profile name
url = "https://starknet-sepolia.infura.io/v3/c721c6ee60924e8a9f30b5ab3e401c67"   # Url of the RPC provider                      # Path to the file with the account data
account = "test_account"                                     # Account from `accounts_file` or default account file that will be used for the transactions                                 # Path to the keystore file
wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
show-explorer-links = true  

[sncast.accounts.test_account]                           # Print links pointing to pages with transaction details in the chosen block explorer
address = "${ACCOUNT_ADDRESS}"
private_key = "${ACCOUNT_PRIVATE_KEY}"